# Default values for spring-petclinic
# This is a YAML-formatted file

# Application configuration
app:
  name: spring-petclinic
  version: "3.5.0"
  
# Image configuration
image:
  repository: "" # Will be set by CI/CD pipeline
  tag: "" # Will be set by CI/CD pipeline
  pullPolicy: IfNotPresent
  registry: ""
  registryUsername: ""
  registryPassword: ""

# Image pull secrets for private registries
imagePullSecrets:
  - name: jfrog-registry-secret

# Service account
serviceAccount:
  create: true
  name: spring-petclinic-sa
  annotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Deployment configuration
replicaCount: 2

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: petclinic.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Auto-scaling configuration
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector, tolerations, and affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Spring Boot configuration
springboot:
  profiles:
    active: postgres
  jvm:
    opts: "-Xmx256m -Xms256m"

# Database configuration
database:
  # Connection details (will be injected from secrets)
  host: ""
  port: 5432
  name: petclinic
  username: ""
  password: ""

# PostgreSQL subchart configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "" # Will be set from GitHub secrets
    username: petclinic
    password: "" # Will be set from GitHub secrets
    database: petclinic
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        memory: 256Mi
        cpu: 250m
      requests:
        memory: 128Mi
        cpu: 100m
  metrics:
    enabled: true
    resources:
      limits:
        memory: 256Mi
        cpu: 250m
      requests:
        memory: 128Mi
        cpu: 100m

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false

# External secrets configuration (for GitHub secrets integration)
externalSecrets:
  enabled: true
  secretStore:
    name: github-secret-store
    kind: SecretStore
  refreshInterval: 1h
  
# Network policies
networkPolicy:
  enabled: true
  ingress:
    enabled: true
  egress:
    enabled: true 