apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-petclinic.fullname" . }}-db-secret
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
---
{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: jfrog-registry-secret
  labels:
    {{- include "spring-petclinic.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry .Values.image.registryUsername .Values.image.registryPassword (printf "%s:%s" .Values.image.registryUsername .Values.image.registryPassword | b64enc) | b64enc }}
{{- end }} 