{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.secretName }}
  labels:
    {{- include "petclinic-app.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.database.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.database.usernameKey }}
      remoteRef:
        key: petclinic-database
        property: username
    - secretKey: {{ .Values.database.passwordKey }}
      remoteRef:
        key: petclinic-database
        property: password
    - secretKey: postgres-password
      remoteRef:
        key: petclinic-database
        property: postgres-password
{{- end }} 