name: Helm CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/helm/**'  
  pull_request:
    paths:
      - 'infra/helm/**'

jobs:
  helm_check:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint and Template Helm Charts
      id: helm_check
      run: |
        cd ./infra/helm/umbrella-petclinic
        
        # Create output directory for templates
        mkdir -p /tmp/helm-templates
        
        for values_file in env/values-*.yaml; do
          env=$(basename $values_file .yaml | sed 's/values-//')
          echo "Processing environment: $env"
          
          echo "Linting chart for $env..."
          helm lint . -f $values_file
          
          echo "Templating chart for $env..."
          helm template test . -f $values_file > /tmp/helm-templates/template-$env.yaml
          
          echo "Template for $env environment generated successfully"
        done

        echo "All Helm checks completed"
        
        # Store template files for PR comment
        echo "template_files=/tmp/helm-templates/" >> $GITHUB_OUTPUT

    - name: Comment PR with Helm Templates
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          const templateDir = '/tmp/helm-templates/';
          let comment = '## 🔍 Helm Chart Templates Generated\n\n';
          
          try {
            const files = fs.readdirSync(templateDir);
            
            for (const file of files) {
              if (file.endsWith('.yaml')) {
                const env = file.replace('template-', '').replace('.yaml', '');
                const content = fs.readFileSync(path.join(templateDir, file), 'utf8');
                
                comment += `### Environment: \`${env}\`\n\n`;
                comment += '<details>\n<summary>Click to expand template</summary>\n\n';
                comment += '```yaml\n';
                comment += content;
                comment += '\n```\n\n';
                comment += '</details>\n\n';
              }
            }
            
            comment += '---\n*Generated by Helm CI workflow*';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
            
          } catch (error) {
            console.error('Error reading template files:', error);
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '## ❌ Helm Template Generation Failed\n\nUnable to read generated templates. Please check the workflow logs for details.'
            });
          }